### ISSUE TITLE
iOS <14 failing?

### ISSUE THREAD

**Issue by lazmeister** [MatthewKapteyn/MediaPlugin#7]
first off thank you for efforts on this repo/fork! Did you happen to use this on a an device running <iOS14? Android seems to work fine with your code but iOS gives me issues. Going to debug and provide more information, but I wanted to get your thoughts first.

**Comment by MatthewKapteyn** [comment]
Ah, sorry for late reply. The code I added only executes on iOS 14+. If it's older it just calls the original functions. I didn't have any issues running iPhone 6 with iOS 12 and and iPhone 8 while it still had iOS 13. Didn't go back any further than that.

Since then I haven't had the need to go back and re-test. What version of iOS were you testing with? Any crash logs?

**Comment by MatthewKapteyn** [comment]
Oh - i should add. The original code that runs on iOS <14 had a lot of problems with iCloud files. There were some attempts at fixing in the original project but I would still get reports of various problems (gallery not loading properly, some photos not downloading etc). It's just not worth going back to fix anymore.

Local files should work fine.

Oh, and not sure if it's still a problem but there's a known buggy HEIC image in the iPhone simulator. It won't convert to jpg when requested iirc. Not an issue with real HEIC files.

**Comment by MatthewKapteyn** [comment]
going to close for now. not much reason to go back to guarantee support for earlier versions of ios. that being said the old photo picker code won't be removed but it did have plenty of issues in iOS 13 (especially in regards to iCloud gallery)
